query testaggau {
  testaggau(args: { start_time: 0, end_time: 350, resolution: 1 }) {
    au01r
    au01c
    au04r
    au04c
    au09r
    au09c
    au10r
    au10c
    au12r
    au12c
    au14r
    au14c
    grouped_seconds
    min_timestamp
  }
}
