query data_aggregate {
  data_aggregate {
    aggregate {
      stddev {
        AU01_c
        AU01_r
        AU02_c
        AU02_r
        AU04_c
        AU04_r
        AU05_c
        AU05_r
        AU06_c
        AU06_r
        AU07_c
        AU07_r
        AU09_c
        AU09_r
        AU10_c
        AU10_r
        AU12_c
        AU12_r
        AU14_c
        AU14_r
        AU15_c
        AU15_r
        AU17_c
        AU17_r
        AU20_c
        AU20_r
        AU23_c
        AU23_r
        AU25_c
        AU25_r
        AU26_c
        AU26_r
        AU28_c
        AU45_c
        AU45_r
        intensity
        pitch
      }
      avg {
        AU01_c
        AU01_r
        AU02_c
        AU02_r
        AU04_c
        AU04_r
        AU05_c
        AU05_r
        AU06_c
        AU06_r
        AU07_c
        AU07_r
        AU09_c
        AU09_r
        AU10_c
        AU10_r
        AU12_c
        AU12_r
        AU14_c
        AU14_r
        AU15_c
        AU15_r
        AU17_c
        AU17_r
        AU20_c
        AU20_r
        AU23_c
        AU23_r
        AU25_c
        AU25_r
        AU26_c
        AU26_r
        AU28_c
        AU45_c
        AU45_r
        intensity
        pitch
      }
    }
  }
}
