mutation insert_todos($todo: String!, $isPublic: Boolean!, $userId: String) {
  insert_todos(
    objects: { title: $todo, is_public: $isPublic, user_id: $userId }
  ) {
    affected_rows
    returning {
      id
      title
      is_completed
      is_public
      created_at
      user_id
    }
  }
}
