query legend_data {
  legend_data {
    min_au01r
    max_au01r
    min_au02r
    max_au02r
    min_au04r
    max_au04r
    min_au05r
    max_au05r
    min_au06r
    max_au06r
    min_au07r
    max_au07r
    min_au09r
    max_au09r
    min_au10r
    max_au10r
    min_au12r
    max_au12r
    min_au14r
    max_au14r
    min_au15r
    max_au15r
    min_au17r
    max_au17r
    min_au20r
    max_au20r
    min_au23r
    max_au23r
    min_au25r
    max_au25r
    min_au26r
    max_au26r
    min_au45r
    max_au45r
    min_au01c
    max_au01c
    min_au02c
    max_au02c
    min_au04c
    max_au04c
    min_au05c
    max_au05c
    min_au06c
    max_au06c
    min_au07c
    max_au07c
    min_au09c
    max_au09c
    min_au10c
    max_au10c
    min_au12c
    max_au12c
    min_au14c
    max_au14c
    min_au15c
    max_au15c
    min_au17c
    max_au17c
    min_au20c
    max_au20c
    min_au23c
    max_au23c
    min_au25c
    max_au25c
    min_au26c
    max_au26c
    min_au28c
    max_au28c
    min_au45c
    max_au45c
    min_topic
    max_topic
    min_pitch
    max_pitch
    min_intensity
    max_intensity
  }
}
