query getMyTodos($isPublic: Boolean!, $userId: String) {
  todos(
    where: { is_public: { _eq: $isPublic }, user_id: { _eq: $userId } }
    order_by: { created_at: desc }
  ) {
    id
    title
    created_at
    is_completed
    user_id
  }
}
