mutation MyMutation(
  $user_id: Int
  $is_public: Boolean = false
  $title: String = ""
) {
  insert_todos(
    objects: { user_id: $user_id, is_public: $is_public, title: $title }
  ) {
    affected_rows
    returning {
      id
      is_completed
      is_public
      title
      user_id
    }
  }
}
