query todos($is_public: Boolean = true, $user_id: Int) {
  todos(
    where: { is_public: { _eq: $is_public }, user_id: { _eq: $user_id } }
    order_by: { created_at: asc }
  ) {
    id
    title
    user_id
    is_completed
    is_public
    created_at
    updated_at
    user {
      id
      avatar_url
      name
    }
  }
}
